services:
  peacemaker-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_PUBLIC_BASE_URL=${VITE_PUBLIC_BASE_URL}
        - BASE_API_URL=${BASE_API_URL}
        - VERCEL_REVALIDATE_TIME=${VERCEL_REVALIDATE_TIME}
        - VITE_PUBLIC_STATIC_EXPORT=${VITE_PUBLIC_STATIC_EXPORT}
        - VITE_PUBLIC_GOOGLE_ANALYTICS_ID=${VITE_PUBLIC_GOOGLE_ANALYTICS_ID}

    env_file:
      - ".env"
    ports:
      # host:container
      - 80:80
